default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: postgres
  password: postgres

development:
  <<: *default
  database: development

test:
  <<: *default
  database: Task1_test

production:
  <<: *default
  database: Task1_pro